config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   root to: 'home#index'

   resources :categories, only: %i[new create index] do 
    resources :transactions, only: %i[index create new] 
  end

  resources :users, only: %i[index]
  # root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :money_groups, dependent: :destroy
  has_many :operations, through: :money_groups

  validates :name, presence: true, length: { minimum: 3 }
  validates :icon, presence: true

  def ordered_transactions
    operations.order(created_at: :desc)
  end
end

app/models/money_group.rb
class MoneyGroup < ApplicationRecord
  belongs_to :group
  belongs_to :operation

  after_create :increment_amount
  before_destroy :decrement_amount

  private

  def increment_amount
    current_amount = group.total_amount
    group.update(total_amount: current_amount + operation.amount)
  end

  def decrement_amount
    subtracted_amount = group.total_amount - operation.amount
    group.update(total_amount: subtracted_amount)
  end
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :user
  has_many :money_groups, dependent: :destroy
  has_many :groups, through: :money_groups

  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy, foreign_key: 'user_id'
  has_many :operations, dependent: :destroy, foreign_key: 'user_id'

  validates :name, presence: true

  def ordered_groups
    groups.order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
  end

  # # Catch all CanCan errors and alert the user of the exception
  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: :splash

  def index
    @categories = current_user.ordered_groups
  end

  def new
    @category = current_user
    group = Group.new
    respond_to do |format|
      format.html { render :new, locals: { group: } }
    end
  end

  def create
    category = Group.new(category_params)
    category.user = current_user
    respond_to do |format|
      format.html do
        if category.save
          flash[:notice] = 'Category was successfully created.'
          redirect_to categories_path
        else
          flash[:alert] = 'Category was not created.'
          render :new, locals: { group: category }
        end
      end
    end
  end

  private

  def category_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @group = current_user.groups.find(params[:category_id])
    @transactions = @group.ordered_transactions
  end

  def new
    @categories = current_user.ordered_groups
    operation = Operation.new
    id = params[:category_id]
    respond_to do |format|
      format.html { render :new, locals: { operation:, id: } }
    end
  end

  def create
    name = transaction_params[:name]
    amount = transaction_params[:amount]
    categories = transaction_params[:categories]
    transaction = Operation.new(name:, amount:)
    transaction.user = current_user
    respond_to do |format|
      format.html do
        if transaction.save
          create_relation(categories, transaction, params[:id])
        else
          @categories = current_user.groups
          flash.now[:alert] = 'Error: Please make sure to fill all fields with the proper input'
          render :new, status: 422, locals: { operation: transaction, id: params[:category_id] }
        end
      end
    end
  end

  private

  def transaction_params
    params.require(:operation).permit(:name, :amount, categories: [])
  end

  def create_relation(categories, transaction, id)
    # First record is empty so gets deleted
    categories.shift

    # If no category was selected
    if categories.empty?
      @categories = current_user.groups
      flash.now[:alert] = 'Error: Please make sure to fill all fields with the proper input'
      render :new, status: 422, locals: { operation: transaction, id: }
      return
    end

    first_category_id = categories[0]

    # Iterates through the categories and create relationships with the operation
    categories.each_with_index do |category_id, _index|
      group = Group.find(category_id)
      MoneyGroup.create(group:, operation: transaction)
    end
    flash[:notice] = 'Transaction created successfully'
    redirect_to(category_transactions_path(category_id: first_category_id))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    redirect_to new_user_registration_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<section id="categories" class="bg-slate-300 w-full min-h-screen relative flex flex-col justify-between">
  <%= render 'shared/header', :title => 'Categories' %>
  <ul class="groups p-3 flex flex-col w-full gap-3 box-border">
    <% @categories.each do |category| %>
      <li class="w-full">
        <%= link_to category_transactions_path(category_id: category.id), id: "Group-#{category.id}", class: 'group flex justify-between items-center p-3 bg-white flex-wrap gap-5' do %>
          <div class="card flex gap-5 items-center">
            <div class="relative w-24 h-24">
              <img src=<%= category.icon %> alt=<%= category.name %> class="absolute top-0 w-full h-full object-cover" >
            </div>
            <h2 class="text-tertiary-500 text-lg"> <%= category.name %> </h2>
          </div>
          <p class="font-semibold text-lg"> $<%= category.total_amount %> </p>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= link_to 'Add New Category', new_category_path, class: "btn"  %>
</section>

app/views/categories/new.html.erb
<%= render 'shared/header', :title => 'Category' %>
<div class="pt-5 flex flex-col items-center w-full">
  <%= form_with model: group, url: categories_url, method: :post, class: 'w-full flex flex-col items-center' do |f| %>
    <div class="field">
      <%= f.label :name, class: 'hidden' %>
      <%= f.text_field :name, autofocus: true, class: "w-96 border border-slate-300 hover:border-indigo-300  p-4", placeholder: 'Name (Minimun 3 characters)' %>
    </div>

    <div class="field">
      <%= f.label :icon, class: 'hidden' %>
      <%= f.text_field :icon, autofocus: true, class: "w-96 border border-slate-300 hover:border-indigo-300 p-4", placeholder: 'Icon (Please add a proper URL)' %>
    </div>

    <div class="actions mt-5">
      <%= f.submit "Save", class: "px-6 py-2 text-white bg-green-500" %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="relative flex flex-col min-h-screen items-center justify-end box-border w-full p-5">
  <h1 class="absolute top-1/3 mb-5 text-3xl text-tertiary-800 font-semibold italic"> Spendless </h1>
  <div class="flex flex-col items-center w-full max-w-2xl p-5">
    <% if user_signed_in?  %>
      <%= link_to 'Categories', categories_path, class: "px-2 py-3 text-xl uppercase font-light text-white bg-primary-500 mb-2 w-full text-center" %>
    <% else %>
      <%= link_to 'Log in', new_user_session_path, class: "bg-red-500 px-2 py-3 text-xl uppercase font-light text-white mb-2 w-full text-center hover:bg-red-700" %>
      <%= link_to 'Sign up', new_user_registration_path, class: "px-2 py-3 text-xl uppercase font-light text-tertiary-300 mb-2 w-full text-center" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpendlessApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    
  </head>

  <body>
    <% if notice %>
      <p class="absolute top-0 z-20 p-2 text-center text-white bg-secondary-800"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="absolute top-0 z-20 p-2 text-center text-white bg-red-800"><%= alert %></p>  
    <% end %>
    <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_header.html.erb
<header class="flex p-5 sticky top-0 text-white bg-blue-400 justify-center z-20 box-border">
  <%= link_to '/', class: 'absolute left-3 top-1/3 px-2', id: 'Home' do %>
    <span class="fa-solid fa-circle-arrow-left text-2xl font-bold">
    </span>
  <% end %>
  <h2 class="text-xl xl:text-2xl uppercase text-light"><%= title %></h2>
  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete, class: 'absolute right-0 bottom-0 h-full flex items-center px-2 box-border' do %>
      <span class="fa-solid fa-arrow-right-to-bracket text-2xl font-bold">
      </span>
    <% end %>
  <% end %>
</header>

app/views/transactions/index.html.erb
<section id="transactions" class="bg-slate-300 w-full min-h-screen relative flex flex-col justify-between">
  <%= render 'shared/header', :title => 'Transactions' %>
  <div class="w-full flex justify-between items-center p-3 bg-white m-6 mx-4 mr-4">
    <h2 class="text-xl font-semibold"> Total amount: $<%= @group.total_amount %> </h2>
  </div>
  <ul class="transactions p-3 flex flex-col w-full gap-3 box-border">
    <% @transactions.each do |transaction| %>
      <li class="transaction w-full flex justify-between items-center p-3 bg-white flex-wrap gap-5">
        <h2 class="text-tertiary-500 text-lg"> <%= transaction.name %> </h2>
        <p class="font-semibold text-lg"> $<%= transaction.amount %> </p>
      </li>
    <% end %>
  </ul>
  <%= link_to 'Add a new transaction', new_category_transaction_path(category_id: @group.id), class: "btn" %>
</section>

app/views/transactions/new.html.erb
<%= render 'shared/header', :title => 'Transaction' %>
<div class="py-5 flex flex-col items-center w-full">
  <%= form_with model: operation, url: category_transactions_url(category_id: id), method: :post, class: 'w-full flex flex-col items-center' do |f| %>
    <div class="field">
      <%= f.label :name, class: 'hidden' %>
      <%= f.text_field :name, autofocus: true, class: "w-96 border border-slate-300 hover:border-indigo-300   p-4", placeholder: 'Name (Minimun 3 characters)' %>
    </div>

    <div class="field">
      <%= f.label :amount, class: 'hidden' %>
      <%= f.number_field :amount, autofocus: true, class: "w-96 border border-slate-300 hover:border-indigo-300   p-4", placeholder: 'Amount (Greater than 0)' %>
    </div>

    <div class="field flex flex-col mt-5" >
      <%= f.label :categories, class: "text-xl text-tertiary-500 mb-3" %>
      <%= f.select :categories, @categories.map { |t| [t.name, t.id]}, { :selected => id }, { :multiple => true, class: "categories w-96 h-72 border border-slate-300 hover:border-indigo-300   text-tertiary-500" } %>
    </div>

    <div class="actions mt-5">
      <%= f.submit "Save", class: "px-6 py-2 text-white bg-green-500" %>
    </div>
  <% end %>
</div>